const videosData = [
    {
        id: 1,
        title: "KABILANCI",
        description: "A thrilling action movie about revenge and justice.",
        imgUrl: "https://ucarecdn.com/695bce5b-3fb6-4254-a406-8c06977c260e/-/preview/720x963/",
        carouselCover: "https://ucarecdn.com/695bce5b-3fb6-4254-a406-8c06977c260e/-/preview/720x963/",
        videoUrl: "https://drive.google.com/file/d/1CWOELtePqeDDI-t07aWB0NAWQXlvH-ul/preview",
        category: "Kannywood",
        genre: "Action",
        year: "2023",
        tags: ["Action", "Drama", "Revenge"],
        type: "Movie",
        trending: true,
        views: 1250000,
        rating: 4.5
    },
    {
        id: 2,
        title: "ZAKIN HUKUMA",
        description: "A heartwarming drama about family bonds and traditions.",
        imgUrl: "https://ucarecdn.com/5332d0cd-7915-4111-a6e7-0037f9a2ca51/-/preview/562x1000/",
        carouselCover: "https://ucarecdn.com/5332d0cd-7915-4111-a6e7-0037f9a2ca51/-/preview/562x1000/",
        videoUrl: "https://drive.google.com/file/d/1qaPa0odvnAbmf0WBIu6TYcCXGU1xBTI0/preview",
        category: "Kannywood",
        genre: "Drama",
        year: "2022",
        tags: ["Drama", "Family", "Tradition"],
        type: "Movie",
        trending: false,
        views: 980000,
        rating: 4.2
    },
    {
        id: 3,
        title: "GIDAN GIDAN",
        description: "A comedy about a family with many secrets.",
        imgUrl: "https://ucarecdn.com/b366b273-9c99-49a7-8b4f-8f052f4b75dd/-/preview/666x1000/",
        carouselCover: "https://ucarecdn.com/b366b273-9c99-49a7-8b4f-8f052f4b75dd/-/preview/666x1000/",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_3",
        category: "Kannywood",
        genre: "Comedy",
        year: "2023",
        tags: ["Comedy", "Family", "Secrets"],
        type: "Movie",
        trending: true,
        views: 1450000,
        rating: 4.7
    },
    {
        id: 4,
        title: "HANYA RAI",
        description: "A romantic story about love against all odds.",
        imgUrl: "https://ucarecdn.com/140b370c-78ae-428e-bdd4-a0f53646ab3d/-/preview/666x1000/",
        carouselCover: "https://ucarecdn.com/140b370c-78ae-428e-bdd4-a0f53646ab3d/-/preview/666x1000/",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_4",
        category: "Kannywood",
        genre: "Romance",
        year: "2022",
        tags: ["Romance", "Drama", "Love"],
        type: "Movie",
        trending: false,
        views: 870000,
        rating: 4.0
    },
    {
        id: 5,
        title: "ZAMANIN DA",
        description: "A historical epic set in ancient Hausa kingdom.",
        imgUrl: "https://short-link.me/QSz4",
        carouselCover: "https://short-link.me/QSz4",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_5",
        category: "Kannywood",
        genre: "Historical",
        year: "2023",
        tags: ["Historical", "Epic", "Kingdom"],
        type: "Movie",
        trending: true,
        views: 1120000,
        rating: 4.6
    },
    {
        id: 6,
        title: "RANAR DA",
        description: "A thrilling adventure through the Sahara desert.",
        imgUrl: "https://ucarecdn.com/83d20f2f-225c-47a7-bab1-29b56377c839/-/preview/666x1000/",
        carouselCover: "https://ucarecdn.com/83d20f2f-225c-47a7-bab1-29b56377c839/-/preview/666x1000/",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_6",
        category: "Kannywood",
        genre: "Adventure",
        year: "2022",
        tags: ["Adventure", "Desert", "Survival"],
        type: "Movie",
        trending: false,
        views: 760000,
        rating: 3.9
    },
    {
        id: 7,
        title: "ALJANNA",
        description: "A spiritual journey of faith and redemption.",
        imgUrl: "https://ucarecdn.com/921f18c2-f832-448d-bf26-dfca56674596/-/preview/666x1000/",
        carouselCover: "https://ucarecdn.com/921f18c2-f832-448d-bf26-dfca56674596/-/preview/666x1000/",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_7",
        category: "Kannywood",
        genre: "Religious",
        year: "2023",
        tags: ["Religious", "Faith", "Redemption"],
        type: "Movie",
        trending: true,
        views: 1320000,
        rating: 4.8
    },
    {
        id: 8,
        title: "MUTUM",
        description: "A psychological thriller about a man with dual identity.",
        imgUrl: "https://bit.ly/3HqoQHR",
        carouselCover: "https://bit.ly/3HqoQHR",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_8",
        category: "Kannywood",
        genre: "Thriller",
        year: "2022",
        tags: ["Thriller", "Psychological", "Mystery"],
        type: "Movie",
        trending: false,
        views: 920000,
        rating: 4.3
    },
    {
        id: 9,
        title: "SARARI",
        description: "A musical drama about dreams and aspirations.",
        imgUrl: "https://ucarecdn.com/9566d727-cec4-431b-be6e-5a718b7602db/-/preview/666x1000/",
        carouselCover: "https://ucarecdn.com/9566d727-cec4-431b-be6e-5a718b7602db/-/preview/666x1000/",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_9",
        category: "Kannywood",
        genre: "Musical",
        year: "2023",
        tags: ["Musical", "Drama", "Dreams"],
        type: "Movie",
        trending: true,
        views: 1180000,
        rating: 4.4
    },
    {
        id: 10,
        title: "KWANA",
        description: "A sci-fi adventure set in futuristic Nigeria.",
        imgUrl: "https://bit.ly/4dHCFh0",
        carouselCover: "https://bit.ly/4dHCFh0",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_10",
        category: "Kannywood",
        genre: "Sci-Fi",
        year: "2022",
        tags: ["Sci-Fi", "Future", "Technology"],
        type: "Movie",
        trending: false,
        views: 1050000,
        rating: 4.1
    },
    {
        id: 11,
        title: "WAKA",
        description: "A documentary about Hausa music and culture.",
        imgUrl: "https://short-link.me/-eIS",
        carouselCover: "https://short-link.me/-eIS",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_11",
        category: "Kannywood",
        genre: "Documentary",
        year: "2023",
        tags: ["Documentary", "Music", "Culture"],
        type: "Movie",
        trending: true,
        views: 890000,
        rating: 4.0
    },
    {
        id: 12,
        title: "DANGA",
        description: "A war epic about courage and sacrifice.",
        imgUrl: "https://short-link.me/-eIS",
        carouselCover: "https://short-link.me/-eIS",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_12",
        category: "Kannywood",
        genre: "War",
        year: "2022",
        tags: ["War", "Courage", "Sacrifice"],
        type: "Movie",
        trending: false,
        views: 950000,
        rating: 4.2
    },
    {
        id: 13,
        title: "GASKIYA",
        description: "A crime thriller about corruption and truth.",
        imgUrl: "https://ucarecdn.com/b366b273-9c99-49a7-8b4f-8f052f4b75dd/-/preview/666x1000/",
        carouselCover: "https://ucarecdn.com/b366b273-9c99-49a7-8b4f-8f052f4b75dd/-/preview/666x1000/",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_13",
        category: "Kannywood",
        genre: "Crime",
        year: "2023",
        tags: ["Crime", "Thriller", "Corruption"],
        type: "Movie",
        trending: true,
        views: 1280000,
        rating: 4.6
    },
    {
        id: 14,
        title: "KIRARI",
        description: "A fantasy adventure with magical elements.",
        imgUrl: "https://ucarecdn.com/9n1c0e7c-3e4a-4b8b-9e0a-1a2b3c4d5e6f/-/preview/300x450/",
        carouselCover: "https://ucarecdn.com/9n1c0e7c-3e4a-4b8b-9e0a-1a2b3c4d5e6f/-/preview/600x320/",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_14",
        category: "Kannywood",
        genre: "Fantasy",
        year: "2022",
        tags: ["Fantasy", "Magic", "Adventure"],
        type: "Movie",
        trending: false,
        views: 840000,
        rating: 3.8
    },
    {
        id: 15,
        title: "ZUCI",
        description: "A horror film about supernatural forces.",
        imgUrl: "https://ucarecdn.com/0o1c0e7c-3e4a-4b8b-9e0a-1a2b3c4d5e6f/-/preview/300x450/",
        carouselCover: "https://ucarecdn.com/0o1c0e7c-3e4a-4b8b-9e0a-1a2b3c4d5e6f/-/preview/600x320/",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_15",
        category: "Kannywood",
        genre: "Horror",
        year: "2023",
        tags: ["Horror", "Supernatural", "Fear"],
        type: "Movie",
        trending: true,
        views: 1100000,
        rating: 4.3
    },
    {
        id: 16,
        title: "HOLLYWOOD ACTION",
        description: "An action-packed thriller from Hollywood.",
        imgUrl: "https://ucarecdn.com/1p1c0e7c-3e4a-4b8b-9e0a-1a2b3c4d5e6f/-/preview/300x450/",
        carouselCover: "https://ucarecdn.com/1p1c0e7c-3e4a-4b8b-9e0a-1a2b3c4d5e6f/-/preview/600x320/",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_16",
        category: "Hollywood",
        genre: "Action",
        year: "2023",
        tags: ["Action", "Thriller", "Hollywood"],
        type: "Movie",
        trending: true,
        views: 2500000,
        rating: 4.7
    },
    {
        id: 17,
        title: "BOLLYWOOD ROMANCE",
        description: "A romantic drama from Bollywood.",
        imgUrl: "https://ucarecdn.com/2q1c0e7c-3e4a-4b8b-9e0a-1a2b3c4d5e6f/-/preview/300x450/",
        carouselCover: "https://short-link.me/QSiT",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_17",
        category: "Bollywood",
        genre: "Romance",
        year: "2023",
        tags: ["Romance", "Drama", "Bollywood"],
        type: "Movie",
        trending: true,
        views: 3200000,
        rating: 4.5
    },
    {
        id: 18,
        title: "NOLLYWOOD DRAMA",
        description: "A family drama from Nollywood.",
        imgUrl: "https://ucarecdn.com/3r1c0e7c-3e4a-4b8b-9e0a-1a2b3c4d5e6f/-/preview/300x450/",
        carouselCover: "https://short-link.me/QSiT",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_18",
        category: "Nollywood",
        genre: "Drama",
        year: "2023",
        tags: ["Drama", "Family", "Nollywood"],
        type: "Movie",
        trending: false,
        views: 1800000,
        rating: 4.1
    },
    {
        id: 19,
        title: "HOLLYWOOD COMEDY",
        description: "A hilarious comedy from Hollywood.",
        imgUrl: "https://short-link.me/QSiT",
        carouselCover: "https://short-link.me/QSiT",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_19",
        category: "Hollywood",
        genre: "Comedy",
        year: "2023",
        tags: ["Comedy", "Humor", "Hollywood"],
        type: "Movie",
        trending: true,
        views: 2100000,
        rating: 4.4
    },
    {
        id: 20,
        title: "BOLLYWOOD ACTION",
        description: "An action-packed movie from Bollywood.",
        imgUrl: "https://ucarecdn.com/5t1c0e7c-3e4a-4b8b-9e0a-1a2b3c4d5e6f/-/preview/300x450/",
        carouselCover: "https://ucarecdn.com/5t1c0e7c-3e4a-4b8b-9e0a-1a2b3c4d5e6f/-/preview/600x320/",
        videoUrl: "https://youtube.com/embed/VIDEO_ID_20",
        category: "Bollywood",
        genre: "Action",
        year: "2023",
        tags: ["Action", "Adventure", "Bollywood"],
        type: "Movie",
        trending: false,
        views: 2700000,
        rating: 4.3
    }
];
